# Fly.io configuration for Legal AI Agent
app = "legal-ai-agent-rahaf"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONPATH = "/app"
  VECTOR_STORE_PATH = "data/law_vector_store"
  CORS_ORIGINS = "*"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[processes]
  app = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --workers 1"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
